name: AWS Credential Test

on:
  push:
    branches:
      - main

jobs:
  test-aws-credentials:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install AWS CLI
      run: |
        python3 -m pip install --upgrade pip
        pip install awscli

    - name: List S3 Buckets
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
      run: |
        aws s3 ls
